export enum Holiday {
	ANZAC_DAY,
	ANZAC_DAY_MONDAYISED,
	WAITANGI_DAY,
	WAITANGI_DAY_MONDAYISED,

	GOOD_FRIDAY,
	EASTER_SUNDAY,
	EASTER_MONDAY,

	LABOUR_DAY,
	MATARIKI,
	SOVEREIGNS_BIRTHDAY,

	QUEEN_ELIZABETH_II_REMEMBRANCE_DAY,
}
